### ISSUE TITLE
failed when loading NEW GAME, 

### ISSUE THREAD

**Issue by haityang** [raynorpat/Doom3#2]
DOOM 1.3.1.1304 MacOSX-universal Dec 27 2015 00:12:25
loopback
IP: 192.168.0.103
NetMask: 255.255.255.0
------ Initializing File System ------
Loaded pk4 /Users/yht/Library/Application Support/Doom 3/base/pak000.pk4 with checksum 0x28d208f1
Loaded pk4 /Users/yht/Library/Application Support/Doom 3/base/pak001.pk4 with checksum 0x40244be0
Loaded pk4 /Users/yht/Library/Application Support/Doom 3/base/pak002.pk4 with checksum 0xc51ecdcd
Loaded pk4 /Users/yht/Library/Application Support/Doom 3/base/pak003.pk4 with checksum 0xcd79d028
Loaded pk4 /Users/yht/Library/Application Support/Doom 3/base/pak004.pk4 with checksum 0x765e4f8b
Current search path:
/Users/yht/Library/Application Support/Doom 3/base
/Users/yht/Library/Application Support/Doom 3/base/pak004.pk4 (5137 files)
/Users/yht/Library/Application Support/Doom 3/base/pak003.pk4 (4676 files)
/Users/yht/Library/Application Support/Doom 3/base/pak002.pk4 (6120 files)
/Users/yht/Library/Application Support/Doom 3/base/pak001.pk4 (8972 files)
/Users/yht/Library/Application Support/Doom 3/base/pak000.pk4 (2698 files)
/Users/yht/Github/Doom3/neo/sys/osx/build/Release/base
game DLL: 0x0 in pak: 0x0
Addon pk4s:
## ----- Initializing Decls -----

------- Initializing renderSystem --------
## renderSystem initialized.

4966 strings read from strings/english.lang
Couldn't open journal files
execing editor.cfg
execing default.cfg
Unknown command '#'
execing DoomConfig.cfg
couldn't exec autoexec.cfg
4966 strings read from strings/english.lang
----- Initializing Sound System ------
## sound system initialized.

----- R_InitOpenGL -----
Initializing OpenGL subsystem
  fullscreen: no
 1024 768 Windowed
ok
## FIXME: Sys_UnfadeScreen

------- Input Initialization -------
5 sound device(s)
  0: ID 46, Built-in Microphone - Apple Inc.
  1: ID 53, Built-in Output - Apple Inc.
  2: ID 38, Adobe Encore DVD 6.0 - Apple Inc.
  3: ID 39, Prelude 1.0 - Apple Inc.
  4: ID 40, Premiere Pro 6.0 - Apple Inc.
select default device, ID 53
current nominal rate: 44100
current frame size: 512
frame size allowed range: 14 4096
setting frame size to: 4096
using stereo channel IDs 1 2
...using GL_ARB_multitexture
...using GL_ARB_texture_cube_map
...using GL_ARB_texture_non_power_of_two
...using GL_ARB_texture_compression
...using GL_EXT_texture_compression_s3tc
...using GL_EXT_texture_filter_anisotropic
   maxTextureAnisotropy: 16.000000
...using GL_1.4_texture_lod_bias
...using GL_EXT_stencil_wrap
...using GL_2.0_separate_stencil
X..GL_ARB_map_buffer_range not found
...using GL_ARB_vertex_buffer_object
...using GL_ARB_vertex_program
X..EXT_depth_bounds_test not found
...using GL_ARB_shading_language_100
----- R_ReloadGLSLPrograms -----
gl2progs/common/cubeNormalReflect.vs
gl2progs/common/cubeNormalReflect.fs
gl2progs/common/cubeReflect.vs
gl2progs/common/cubeReflect.fs
gl2progs/common/depth.vs
gl2progs/common/depth.fs
gl2progs/common/depthWithMask.vs
gl2progs/common/depthWithMask.fs
gl2progs/common/stencil.vs
gl2progs/common/stencil.fs
gl2progs/common/texture.vs
gl2progs/common/texture.fs
gl2progs/common/textureProjected.vs
gl2progs/common/textureProjected.fs
gl2progs/interaction.vs
gl2progs/interaction.fs
gl2progs/interactionAmbient.vs
## gl2progs/interactionAmbient.fs

using ARB_vertex_buffer_object memory
--------- Initializing Game ----------
gamename: baseDOOM-1
gamedate: Dec 27 2015
Initializing event system
...462 event definitions
Initializing class hierarchy
...109 classes, 258720 bytes for event callbacks
Initializing scripts
Compiled '': 0.0 ms
---------- Compile stats ----------

Memory usage:
     Strings: 79, 12592 bytes
  Statements: 67783, 1355660 bytes
   Functions: 2108, 250452 bytes
   Variables: 147320 bytes
    Mem used: 2476244 bytes
 Static data: 2277552 bytes
   Allocated: 3283340 bytes
 Thread size: 7068 bytes

...6 aas types
## game initialized.

-------- Initializing Session --------
## session initialized

--- Common Initialization Complete ---
terminal support enabled ( use +set in_tty 0 to disabled )
pid: 5200
2047 MB System Memory
256 MB Video Memory
Async thread started
WARNING: idSession: triggering mainmenu watchdog
WARNING: Unknown string id #str_07183
WARNING: Unknown string id #str_07023
WARNING: Unknown string id #str_07183
WARNING: Unknown string id #str_07024
WARNING: Unknown string id #str_07021
WARNING: Unknown string id #str_07183
WARNING: Unknown string id #str_07055
WARNING: Unknown string id #str_07025
WARNING: Unknown string id #str_07026
WARNING: Unknown string id #str_07029
WARNING: Unknown string id #str_07028
WARNING: Unknown string id #str_07183
WARNING: Unknown string id #str_07054
WARNING: Unknown string id #str_07183
WARNING: Unknown string id #str_07131
WARNING: Unknown string id #str_07183
WARNING: Unknown string id #str_07183
WARNING: Unknown string id #str_07132
WARNING: Unknown string id #str_07050
WARNING: Unknown string id #str_07049
WARNING: Unknown string id #str_07053
WARNING: Unknown string id #str_07183
WARNING: Unknown string id #str_07056
WARNING: Unknown string id #str_07018
WARNING: Unknown string id #str_07130
WARNING: Unknown string id #str_07183
WARNING: Unknown string id #str_07040
WARNING: Unknown string id #str_07044
WARNING: Unknown string id #str_07047
WARNING: Unknown string id #str_07041
WARNING: Unknown string id #str_07042
WARNING: Unknown string id #str_07038
WARNING: Unknown string id #str_07036
WARNING: Unknown string id #str_07037
WARNING: Unknown string id #str_07186
WARNING: Unknown string id #str_07186
WARNING: Unknown string id #str_07212
## --------- Game Map Shutdown ----------

reloading guis/mainmenu.gui.
reloading guis/restart.gui.
reloading guis/gameover.gui.
reloading guis/msg.gui.
reloading guis/takeNotes.gui.
reloading guis/intro.gui.
--------- Map Initialization ---------
Map: game/mars_city1
WARNING: deprecated token 'Program' in material 'textures/glass/glass2'
WARNING: deprecated token 'Program' in material 'textures/glass/glass1'
WARNING: deprecated token 'vertexProgram' in material 'textures/sfx/vpalphaglass'
----------- Game Map Init ------------
collision data:
   421 models
 30823 vertices (722 KB)
 54551 edges (1917 KB)
 22257 polygons (1564 KB)
  4068 brushes (556 KB)
 12449 nodes (340 KB)
 43444 polygon refs (339 KB)
 14219 brush refs (111 KB)
 18352 internal edges
  1461 sharp edges
     0 contained polygons removed
     0 polygons merged
  5551 KB total memory used
0 msec to load collision data.
map bounds are (19640.0, 22168.0, 29496.0)
max clip sector is (1227.5, 1385.5, 1843.5)
    2 KB passage memory used to build PVS
    0 msec to calculate PVS
   56 areas
  110 portals
    9 areas visible on average
  448 bytes PVS data
[Load AAS]
loading maps/game/mars_city1.aas48
done.
[Load AAS]
loading maps/game/mars_city1.aas96
[Load AAS]
loading maps/game/mars_city1.aas_guardian
[Load AAS]
loading maps/game/mars_city1.aas_mancubus
[Load AAS]
loading maps/game/mars_city1.aas_sabaoth
[Load AAS]
loading maps/game/mars_city1.aas_cyberdemon
Entering doom_main()
Exiting doom_main()
Spawning entities
WARNING: Could not spawn 'target_tip'.  Class 'idTarget_Tip' not found on 'target_tip_11'.
WARNING: Could not spawn 'func_remove'.  Class 'idTarget_Remove' not found on 'func_remove_12'.
WARNING: Could not spawn 'func_remove'.  Class 'idTarget_Remove' not found on 'func_remove_11'.
loaded collision model models/mapobjects/com/platguistand/mc_platguistand.lwo
WARNING: Could not spawn 'func_remove'.  Class 'idTarget_Remove' not found on 'func_remove_10'.
WARNING: marscity_cinematic_sarge_1 has no AAS file
WARNING: marscity_cinematic_sarge2_1 has no AAS file
loaded collision model models/mapobjects/filler/burgerboxopen.lwo
WARNING: Could not spawn 'func_remove'.  Class 'idTarget_Remove' not found on 'func_remove_9'.
WARNING: Could not spawn 'func_remove'.  Class 'idTarget_Remove' not found on 'func_remove_8'.
WARNING: deprecated token 'program' in material 'textures/sfx/vppinch_bfgbolt'
WARNING: Could not spawn 'func_remove'.  Class 'idTarget_Remove' not found on 'func_remove_7'.
WARNING: Could not spawn 'func_remove'.  Class 'idTarget_Remove' not found on 'fredfunc_remove_7'.
WARNING: Could not spawn 'func_remove'.  Class 'idTarget_Remove' not found on 'remove_recep_b4_sarge'.
WARNING: Could not spawn 'target_tip'.  Class 'idTarget_Tip' not found on 'target_tip_8'.
loaded collision model models/mapobjects/lab/diamondbox/diamondbox_sm.lwo
WARNING: Could not spawn 'target_tip'.  Class 'idTarget_Tip' not found on 'target_tip_7'.
WARNING: Could not spawn 'target_tip'.  Class 'idTarget_Tip' not found on 'target_tip_6'.
WARNING: Could not spawn 'target_tip'.  Class 'idTarget_Tip' not found on 'target_tip_4'.
WARNING: Could not spawn 'target_tip'.  Class 'idTarget_Tip' not found on 'target_tip_3'.
WARNING: Could not spawn 'target_tip'.  Class 'idTarget_Tip' not found on 'target_tip_2'.
WARNING: Could not spawn 'target_tip'.  Class 'idTarget_Tip' not found on 'target_tip_1'.
WARNING: Could not spawn 'target_giveemail'.  Class 'idTarget_GiveEmail' not found on 'target_giveemail_2'.
loaded collision model models/mapobjects/com/modconsole1.lwo
WARNING: Could not spawn 'target_primaryobjective'.  Class 'idTarget_SetPrimaryObjective' not found on 'target_primaryobjective_2'.
WARNING: Could not spawn 'target_null'.  Class 'idTarget' not found on 'target_null_2'.
WARNING: Could not spawn 'target_null'.  Class 'idTarget' not found on 'target_null_1'.
WARNING: Could not spawn 'target_primaryobjective'.  Class 'idTarget_SetPrimaryObjective' not found on 'target_primaryobjective_1'.
WARNING: Could not spawn 'func_remove'.  Class 'idTarget_Remove' not found on 'func_remove_6'.
WARNING: Could not spawn 'target_setshaderparm'.  Class 'idTarget_SetShaderParm' not found on 'target_setshaderparm_2'.
WARNING: Could not spawn 'target_entity_fadeout'.  Class 'idTarget_FadeEntity' not found on 'bioscan_fadeout'.
WARNING: Could not spawn 'func_remove'.  Class 'idTarget_Remove' not found on 'func_remove_5'.
WARNING: deprecated token 'vertexProgram' in material 'textures/sfx/vp1'
WARNING: Could not spawn 'func_remove'.  Class 'idTarget_Remove' not found on 'func_remove_4'.
WARNING: Could not spawn 'func_remove'.  Class 'idTarget_Remove' not found on 'func_remove_3'.
loaded collision model models/mapobjects/filler/burgereat.lwo
loaded collision model models/mapobjects/filler/burgerboxclose.lwo
loaded collision model models/mapobjects/filler/mkeyboard.lwo
loaded collision model models/mapobjects/lights/florescent_bulbflare.ASE
loaded collision model models/mapobjects/base/misc/emerlight.ase
loaded collision model models/mapobjects/monitors/controlmonitor.lwo
WARNING: Could not spawn 'target_setshaderparm'.  Class 'idTarget_SetShaderParm' not found on 'target_setshaderparm_1'.
loaded collision model models/mapobjects/doors/mcitydoor2l.lwo
loaded collision model models/mapobjects/doors/mcitydoor2r.lwo
loaded collision model models/mapobjects/doors/mcdoor2frame.lwo
loaded collision model models/mapobjects/tables/conf_table/conf_table.lwo
loaded collision model models/mapobjects/filler/cola1.lwo
loaded collision model models/mapobjects/filler/foamcup.lwo
loaded collision model models/mapobjects/signs/marquee/marquee.lwo
loaded collision model models/mapobjects/doors/mcitydoorframe.lwo
loaded collision model models/mapobjects/doors/mcitydoorframegui.lwo
loaded collision model models/items/keycard/keycard3.lwo
loaded collision model models/mapobjects/doors/mcitydoor.lwo
loaded collision model models/mapobjects/cpu/pullhandle.lwo
loaded collision model models/mapobjects/doors/delelev/delelevlf.lwo
loaded collision model models/mapobjects/guiobjects/techdrpanel1/techdrpanel1.lwo
loaded collision model models/mapobjects/doors/delelev/delelevrt.lwo
loaded collision model models/mapobjects/filler/ktable.lwo
loaded collision model models/mapobjects/cpu/heater.lwo
loaded collision model models/mapobjects/cpu/heater2.lwo
loaded collision model models/mapobjects/cpu/comrack2.lwo
loaded collision model models/mapobjects/lab/sink2/sink2.lwo
loaded collision model models/mapobjects/filler/sodamachine.lwo
loaded collision model models/mapobjects/filler/binder1.ase
loaded collision model models/mapobjects/lab/bubbler2/bubbler2.lwo
loaded collision model models/mapobjects/filler/tbox7.ase
loaded collision model models/mapobjects/filler/binder3.ase
loaded collision model models/mapobjects/chairs/modchair/modtable.lwo
loaded collision model models/mapobjects/chairs/modchair/modseat.lwo
loaded collision model models/mapobjects/chairs/modchair/modarm.lwo
removed 2 degenerate triangles
loaded collision model models/mapobjects/lab/newfridge/newfridge.lwo
loaded collision model models/mapobjects/filler/paper1.ase
loaded collision model models/mapobjects/filler/tbox6.ase
loaded collision model models/mapobjects/filler/tbox_open.ase
loaded collision model models/mapobjects/filler/toolchest.lwo
loaded collision model models/mapobjects/doors/deldoor1/deldoor1frm.lwo
loaded collision model models/mapobjects/doors/deldoor1/deldoor1.lwo
loaded collision model models/mapobjects/com/modconsole2.lwo
loaded collision model models/mapobjects/com/modconsole5.lwo
loaded collision model models/mapobjects/cpu/cpumaze1.lwo
loaded collision model models/mapobjects/doors/deldoor1/deldoor1win.lwo
loaded collision model models/mapobjects/com/modconsole4.lwo
loaded collision model models/mapobjects/lab/gizmo2/gizmo2.lwo
loaded collision model models/mapobjects/lab/autable/autable.lwo
loaded collision model models/mapobjects/lab/roboarm1/roboarm1.lwo
loaded collision model models/mapobjects/utility/tecknob2/tecknob2.lwo
loaded collision model models/mapobjects/cpu/comrack.lwo
loaded collision model models/mapobjects/tables/gendesk/gendesk2.lwo
loaded collision model models/mapobjects/filler/tbox2.ase
loaded collision model models/mapobjects/cpu/serverplate.lwo
loaded collision model models/mapobjects/filler/snackmachine.lwo
loaded collision model models/mapobjects/filler/tbox1.ase
loaded collision model models/mapobjects/washroom/clamp.ase
loaded collision model models/mapobjects/washroom/urinal2.ase
loaded collision model models/mapobjects/washroom/dryer.ase
loaded collision model models/mapobjects/washroom/bsink.ase
loaded collision model models/mapobjects/washroom/soap.ase
loaded collision model models/mapobjects/washroom/toilet.ase
loaded collision model models/mapobjects/washroom/tp.ase
loaded collision model models/mapobjects/arcade_machine/arcade_machine.lwo
loaded collision model models/mapobjects/mcity/deskcomp/deskcomp.lwo
loaded collision model models/mapobjects/skmachines/skoverhang.lwo
loaded collision model models/mapobjects/shipping_crates/shipping_crates.lwo
WARNING: Could not spawn 'func_remove'.  Class 'idTarget_Remove' not found on 'func_remove_1'.
WARNING: Could not spawn 'func_remove'.  Class 'idTarget_Remove' not found on 'remplayer'.
WARNING: Could not spawn 'func_remove'.  Class 'idTarget_Remove' not found on 'removeguys'.
WARNING: Could not spawn 'func_remove'.  Class 'idTarget_Remove' not found on 'removebetplayer'.
WARNING: Could not spawn 'func_remove'.  Class 'idTarget_Remove' not found on 'removemarine1'.
loaded collision model models/mapobjects/skmachines/skcube.lwo
loaded collision model models/mapobjects/doors/accesshatch/accesshatch.lwo
loaded collision model models/mapobjects/doors/accesshatch/accesshatchdoor.lwo
loaded collision model models/mapobjects/elevators/elevator.lwo
loaded collision model models/mapobjects/swinglights/swinglight1b.lwo
loaded collision model models/mapobjects/swinglights/swinglight_long_wbulbs_bulb_broken.ase
WARNING: Could not spawn 'target_endlevel'.  Class 'idTarget_EndLevel' not found on 'tim_target_endlevel_1'.
loaded collision model models/mapobjects/filler/keyboard1.ase
loaded collision model models/mapobjects/storagecab/gunrack/gunrackcomp.lwo
loaded collision model models/mapobjects/chairs/modchair/modcorner.lwo
loaded collision model models/mapobjects/shutter/shutter_small.lwo
loaded collision model models/mapobjects/mcity/outside/mc_outside.lwo
loaded collision model models/mapobjects/turrets/ceilingturret1b.lwo
loaded collision model models/mapobjects/mcity/outside/mc_outside2.lwo
loaded collision model models/mapobjects/kiosk/infokiosk2.lwo
WARNING: Could not spawn 'func_remove'.  Class 'idTarget_Remove' not found on 'removesecs'.
loaded collision model models/mapobjects/lab/loadingplatform/loadingplatform.lwo
loaded collision model models/mapobjects/deltakiosk/deltakiosk.lwo
WARNING: Could not spawn 'target_ai_followalternatepath1'.  Class 'idTarget_CallObjectFunction' not found on 'checkinalt1'.
WARNING: Could not spawn 'target_ai_followalternatepath1'.  Class 'idTarget_CallObjectFunction' not found on 'target_ai_followalternatepath1_2'.
WARNING: Could not spawn 'func_remove'.  Class 'idTarget_Remove' not found on 'func_remove_sarge2'.
WARNING: Could not spawn 'func_remove'.  Class 'idTarget_Remove' not found on 'remove_sarge2'.
WARNING: Could not spawn 'func_remove'.  Class 'idTarget_Remove' not found on 'remove_player'.
WARNING: marscity_cinematic_player_sarge has no AAS file
loaded collision model models/mapobjects/hangar/hangar1b.lwo
loaded collision model models/mapobjects/doors/jumbodoor/jumbodoorfrm.lwo
loaded collision model models/mapobjects/hangar/hangar1tower.lwo
loaded collision model models/mapobjects/hangar/rails3.lwo
loaded collision model models/mapobjects/hangar/rails2.lwo
loaded collision model models/mapobjects/hangar/rails1.lwo
loaded collision model models/mapobjects/hangar/rails4.lwo
loaded collision model models/mapobjects/hangar/rails5.lwo
loaded collision model models/mapobjects/hangar/pillar1.lwo
loaded collision model models/mapobjects/hangar/rails6.lwo
loaded collision model models/mapobjects/hangar/marquee.lwo
loaded collision model models/mapobjects/hangar/hangarlamp1.lwo
loaded collision model models/mapobjects/mcity/bioscanner/bioscannereye.lwo
loaded collision model models/mapobjects/tables/gendesk/gendesk1.lwo
loaded collision model models/mapobjects/hangar/hangar2tower.lwo
WARNING: Could not spawn 'target_entity_fadein'.  Class 'idTarget_FadeEntity' not found on 'bioscan_fadein'.
loaded collision model models/mapobjects/monitors/hangingmonitor.lwo
loaded collision model models/mapobjects/signs/ceilingsign/ceilingsign.lwo
WARNING: Could not spawn 'func_remove'.  Class 'idTarget_Remove' not found on 'player_rec_remove'.
WARNING: Could not spawn 'func_remove'.  Class 'idTarget_Remove' not found on 'remove_first_typing_recep'.
WARNING: Could not spawn 'target_ai_followalternatepath1'.  Class 'idTarget_CallObjectFunction' not found on 'target_ai_followalternatepath1_1'.
WARNING: Could not spawn 'target_ai_followalternatepath1'.  Class 'idTarget_CallObjectFunction' not found on 'target_ai_followalternatepath1_2james'.
loaded collision model models/mapobjects/elevators/elevator_door.lwo
loaded collision model models/mapobjects/com/platguistand/platguistand.lwo
loaded collision model models/mapobjects/guiobjects/flatmonitor/flatmonitor.lwo
loaded collision model models/mapobjects/mcity/bioscanner/bioscanbeam.lwo
loaded collision model models/mapobjects/mcity/bioscanner/bioscanner.lwo
loaded collision model models/mapobjects/doors/mcitydoor_glass.lwo
loaded collision model models/mapobjects/lab/fridge1/fridge1_delta2b.lwo
WARNING: deprecated token 'vertexProgram' in material 'textures/sfx/vp1particle2'
WARNING: Couldn't load sound 'guisounds.wav' using default
WARNING: Could not spawn 'target_tip'.  Class 'idTarget_Tip' not found on 'target_tip_9'.
WARNING: Could not spawn 'target_tip'.  Class 'idTarget_Tip' not found on 'target_tip_10'.
loaded collision model models/mapobjects/turrets/ceilingturret1a.lwo
WARNING: Could not spawn 'target_giveemail'.  Class 'idTarget_GiveEmail' not found on 'target_giveemail_3'.
WARNING: Could not spawn 'target_giveemail'.  Class 'idTarget_GiveEmail' not found on 'target_giveemail_4'.
...1969 entities spawned, 0 inhibited

==== Processing events ====
WARNING: Unknown string id #str_07183
WARNING: Unknown string id #str_07023
WARNING: Unknown string id #str_07183
WARNING: Unknown string id #str_07024
WARNING: Unknown string id #str_07021
WARNING: Unknown string id #str_07183
WARNING: Unknown string id #str_07055
WARNING: Unknown string id #str_07025
WARNING: Unknown string id #str_07026
WARNING: Unknown string id #str_07029
WARNING: Unknown string id #str_07028
WARNING: Unknown string id #str_07183
WARNING: Unknown string id #str_07054
WARNING: Unknown string id #str_07183
WARNING: Unknown string id #str_07131
WARNING: Unknown string id #str_07183
WARNING: Unknown string id #str_07183
WARNING: Unknown string id #str_07132
WARNING: Unknown string id #str_07050
WARNING: Unknown string id #str_07049
WARNING: Unknown string id #str_07053
WARNING: Unknown string id #str_07183
WARNING: Unknown string id #str_07056
WARNING: Unknown string id #str_07018
WARNING: Unknown string id #str_07130
WARNING: Unknown string id #str_07183
WARNING: Unknown string id #str_07040
WARNING: Unknown string id #str_07044
WARNING: Unknown string id #str_07047
WARNING: Unknown string id #str_07041
WARNING: Unknown string id #str_07042
WARNING: Unknown string id #str_07038
WARNING: Unknown string id #str_07036
## WARNING: Unknown string id #str_07037

SpawnPlayer: 0
WARNING: deprecated token 'program' in material 'textures/sfx/vpring3'
loaded collision model models/weapons/shell1/mshell_lo.lwo
loaded collision model models/weapons/shell1/sshell_bigger.lwo
TODO: Sys_SetClipboardData
## --------- Game Map Shutdown ----------

---

ERROR: Missing 'WEAPON_NETFIRING' field in script object 'weapon_fists'

---

WARNING: idSession: triggering mainmenu watchdog
WARNING: Unknown string id #str_07183
WARNING: Unknown string id #str_07023
WARNING: Unknown string id #str_07183
WARNING: Unknown string id #str_07024
WARNING: Unknown string id #str_07021
WARNING: Unknown string id #str_07183
WARNING: Unknown string id #str_07055
WARNING: Unknown string id #str_07025
WARNING: Unknown string id #str_07026
WARNING: Unknown string id #str_07029
WARNING: Unknown string id #str_07028
WARNING: Unknown string id #str_07183
WARNING: Unknown string id #str_07054
WARNING: Unknown string id #str_07183
WARNING: Unknown string id #str_07131
WARNING: Unknown string id #str_07183
WARNING: Unknown string id #str_07183
WARNING: Unknown string id #str_07132
WARNING: Unknown string id #str_07050
WARNING: Unknown string id #str_07049
WARNING: Unknown string id #str_07053
WARNING: Unknown string id #str_07183
WARNING: Unknown string id #str_07056
WARNING: Unknown string id #str_07018
WARNING: Unknown string id #str_07130
WARNING: Unknown string id #str_07183
WARNING: Unknown string id #str_07040
WARNING: Unknown string id #str_07044
WARNING: Unknown string id #str_07047
WARNING: Unknown string id #str_07041
WARNING: Unknown string id #str_07042
WARNING: Unknown string id #str_07038
WARNING: Unknown string id #str_07036
WARNING: Unknown string id #str_07037
WARNING: Unknown string id #str_07186
WARNING: Unknown string id #str_07186
WARNING: Unknown string id #str_07212

---

compile smoothly, but can't play. have no idea how resolve the issue...

**Comment by raynorpat** [comment]
Your missing the 1.3.1 patch pk4s.
